In [1]:
# Import Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [2]:
os.getcwd()

'c:\\Users\\HP\\Desktop\\Machine Learning Programing with prajwal'

In [3]:
# Load the Data Set

os.chdir('C:\\Users\\HP\\Downloads\\Batch 93 Day34\\')

In [4]:
dataset=pd.read_csv('Wine.csv')
dataset

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  Customer_Segment  
0     3.92     1065                 1  
1     3.40     1050                 1  
2     3.17     1185                 1  
3     3.45     1480                 1  
4     2.93      735                 1  
..     ...      ...               ...  
173   1.74      740                 3  
174   1.56      750                 3  
175   1.56      835                 3  
176   1.62      840                 3  
177   1.60      560                 3  

[178 rows x 14 columns]

In [5]:
# Create X Variable - Independent Variables

X=dataset.iloc[:,:-1].values
display(pd.DataFrame(X))

0     1     2     3      4     5     6     7     8      9     10  \
0    14.23  1.71  2.43  15.6  127.0  2.80  3.06  0.28  2.29   5.64  1.04   
1    13.20  1.78  2.14  11.2  100.0  2.65  2.76  0.26  1.28   4.38  1.05   
2    13.16  2.36  2.67  18.6  101.0  2.80  3.24  0.30  2.81   5.68  1.03   
3    14.37  1.95  2.50  16.8  113.0  3.85  3.49  0.24  2.18   7.80  0.86   
4    13.24  2.59  2.87  21.0  118.0  2.80  2.69  0.39  1.82   4.32  1.04   
..     ...   ...   ...   ...    ...   ...   ...   ...   ...    ...   ...   
173  13.71  5.65  2.45  20.5   95.0  1.68  0.61  0.52  1.06   7.70  0.64   
174  13.40  3.91  2.48  23.0  102.0  1.80  0.75  0.43  1.41   7.30  0.70   
175  13.27  4.28  2.26  20.0  120.0  1.59  0.69  0.43  1.35  10.20  0.59   
176  13.17  2.59  2.37  20.0  120.0  1.65  0.68  0.53  1.46   9.30  0.60   
177  14.13  4.10  2.74  24.5   96.0  2.05  0.76  0.56  1.35   9.20  0.61   

       11      12  
0    3.92  1065.0  
1    3.40  1050.0  
2    3.17  1185.0  
3    3.45  1480.0  
4    2.93   735.0  
..    ...     ...  
173  1.74   740.0  
174  1.56   750.0  
175  1.56   835.0  
176  1.62   840.0  
177  1.60   560.0  

[178 rows x 13 columns]

In [8]:
# Create Y Variable - Dependent Variables

y=dataset.iloc[:,-1].values
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


In [9]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc_x=sc.fit_transform(X)
display(pd.DataFrame(sc_x))

0         1         2         3         4         5         6   \
0    1.518613 -0.562250  0.232053 -1.169593  1.913905  0.808997  1.034819   
1    0.246290 -0.499413 -0.827996 -2.490847  0.018145  0.568648  0.733629   
2    0.196879  0.021231  1.109334 -0.268738  0.088358  0.808997  1.215533   
3    1.691550 -0.346811  0.487926 -0.809251  0.930918  2.491446  1.466525   
4    0.295700  0.227694  1.840403  0.451946  1.281985  0.808997  0.663351   
..        ...       ...       ...       ...       ...       ...       ...   
173  0.876275  2.974543  0.305159  0.301803 -0.332922 -0.985614 -1.424900   
174  0.493343  1.412609  0.414820  1.052516  0.158572 -0.793334 -1.284344   
175  0.332758  1.744744 -0.389355  0.151661  1.422412 -1.129824 -1.344582   
176  0.209232  0.227694  0.012732  0.151661  1.422412 -1.033684 -1.354622   
177  1.395086  1.583165  1.365208  1.502943 -0.262708 -0.392751 -1.274305   

           7         8         9         10        11        12  
0   -0.659563  1.224884  0.251717  0.362177  1.847920  1.013009  
1   -0.820719 -0.544721 -0.293321  0.406051  1.113449  0.965242  
2   -0.498407  2.135968  0.269020  0.318304  0.788587  1.395148  
3   -0.981875  1.032155  1.186068 -0.427544  1.184071  2.334574  
4    0.226796  0.401404 -0.319276  0.362177  0.449601 -0.037874  
..        ...       ...       ...       ...       ...       ...  
173  1.274310 -0.930179  1.142811 -1.392758 -1.231206 -0.021952  
174  0.549108 -0.316950  0.969783 -1.129518 -1.485445  0.009893  
175  0.549108 -0.422075  2.224236 -1.612125 -1.485445  0.280575  
176  1.354888 -0.229346  1.834923 -1.568252 -1.400699  0.296498  
177  1.596623 -0.422075  1.791666 -1.524378 -1.428948 -0.595160  

[178 rows x 13 columns]

In [10]:
# PCA with N components= None

from sklearn.decomposition import PCA
pca=PCA()
pca_x=pca.fit_transform(sc_x)
pd.DataFrame(pca_x)

0         1         2         3         4         5         6   \
0    3.316751  1.443463 -0.165739 -0.215631  0.693043  0.223880  0.596427   
1    2.209465 -0.333393 -2.026457 -0.291358 -0.257655  0.927120  0.053776   
2    2.516740  1.031151  0.982819  0.724902 -0.251033 -0.549276  0.424205   
3    3.757066  2.756372 -0.176192  0.567983 -0.311842 -0.114431 -0.383337   
4    1.008908  0.869831  2.026688 -0.409766  0.298458  0.406520  0.444074   
..        ...       ...       ...       ...       ...       ...       ...   
173 -3.370524  2.216289 -0.342570  1.058527 -0.574164  1.108788  0.958416   
174 -2.601956  1.757229  0.207581  0.349496  0.255063  0.026465  0.146894   
175 -2.677839  2.760899 -0.940942  0.312035  1.271355 -0.273068  0.679235   
176 -2.387017  2.297347 -0.550696 -0.688285  0.813955 -1.178783  0.633975   
177 -3.208758  2.768920  1.013914  0.596903 -0.895193 -0.296092  0.005741   

           7         8         9         10        11        12  
0   -0.065139 -0.641443  1.020956 -0.451563  0.540810 -0.066239  
1   -1.024416  0.308847  0.159701 -0.142657  0.388238  0.003637  
2    0.344216  1.177834  0.113361 -0.286673  0.000584  0.021717  
3   -0.643593 -0.052544  0.239413  0.759584 -0.242020 -0.369484  
4   -0.416700 -0.326819 -0.078366 -0.525945 -0.216664 -0.079364  
..        ...       ...       ...       ...       ...       ...  
173  0.146097  0.022498 -0.304117  0.139228  0.170786 -0.114427  
174  0.552427  0.097969 -0.206061  0.258198 -0.279431 -0.187371  
175 -0.047024 -0.001222 -0.247997  0.512492  0.698766  0.072078  
176 -0.390829 -0.057448  0.491490  0.299822  0.339821 -0.021866  
177  0.292914 -0.741660 -0.117969 -0.229964 -0.188788 -0.323965  

[178 rows x 13 columns]

In [12]:
# Exaplained Variance Ratio

print(pd.DataFrame(pca.explained_variance_ratio_))

           0
0   0.361988
1   0.192075
2   0.111236
3   0.070690
4   0.065633
5   0.049358
6   0.042387
7   0.026807
8   0.022222
9   0.019300
10  0.017368
11  0.012982
12  0.007952


In [13]:
# PCA with N components = 2
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
pca_x=pca.fit_transform(sc_x)
display(pd.DataFrame(pca_x))

0         1
0    3.316751  1.443463
1    2.209465 -0.333393
2    2.516740  1.031151
3    3.757066  2.756372
4    1.008908  0.869831
..        ...       ...
173 -3.370524  2.216289
174 -2.601956  1.757229
175 -2.677839  2.760899
176 -2.387017  2.297347
177 -3.208758  2.768920

[178 rows x 2 columns]

In [16]:
# Exaplined Varianve Ratio

display(pd.DataFrame(pca.explained_variance_ratio_))

0
0  0.361988
1  0.192075

In [20]:
# Train Test Split

from sklearn.model_selection import train_test_split
pca_x_train,pca_x_test,y_train,y_test=train_test_split(pca_x,y,test_size=0.2,random_state=0)
print(pca_x.shape)
print(pca_x_train.shape)
print(pca_x_test.shape)

(178, 2)
(142, 2)
(36, 2)


In [21]:
# Create Logistic Regression

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(random_state=0)
lr.fit(pca_x_train,y_train)


LogisticRegression(random_state=0)

In [22]:
# Prediction

y_pred=lr.predict(pca_x_test)
print(y_pred)

[1 3 2 1 2 1 1 3 2 2 3 3 1 2 3 2 1 1 2 1 2 1 1 2 2 2 2 2 2 3 1 1 2 1 1 1]


In [25]:
# Display Accuracy

from sklearn.metrics import confusion_matrix,accuracy_score
print(accuracy_score(y_pred,y_test))
cm=confusion_matrix(y_pred,y_test)
print(cm)

0.9722222222222222
[[14  1  0]
 [ 0 15  0]
 [ 0  0  6]]


In [27]:
(15+14+6)/36

0.9722222222222222

In [28]:
# PCA with N Components = 1 and Logistic Regression

from sklearn.decomposition import PCA
pca=PCA(n_components=1)
pca_x=pca.fit_transform(sc_x)
display(pd.DataFrame(pca_x))

0
0    3.316751
1    2.209465
2    2.516740
3    3.757066
4    1.008908
..        ...
173 -3.370524
174 -2.601956
175 -2.677839
176 -2.387017
177 -3.208758

[178 rows x 1 columns]

In [31]:
# Explained Variance Ratio

display(pd.DataFrame(pca.explained_variance_ratio_))

0
0  0.361988

In [32]:
# Train Test Split

from sklearn.model_selection import train_test_split
pca_x_train,pca_x_test,y_train,y_test=train_test_split(pca_x,y,test_size=0.2,random_state=0)
print(pca_x.shape)
print(pca_x_train.shape)
print(pca_x_test.shape)

(178, 1)
(142, 1)
(36, 1)


In [33]:
# Create Logistic Regression

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(random_state=0)
lr.fit(pca_x_train,y_train)


LogisticRegression(random_state=0)

In [34]:
# Prediction

y_pred=lr.predict(pca_x_test)
print(y_pred)

[1 3 1 1 2 2 1 3 2 2 3 3 1 1 3 2 1 1 3 1 1 2 2 2 2 2 2 2 2 3 1 1 3 2 1 1]


In [35]:
# Display Accuracy
from sklearn.metrics import confusion_matrix,accuracy_score
print(accuracy_score(y_test,y_pred))
cm=confusion_matrix(y_test,y_pred)
print(cm)

0.7777777777777778
[[11  3  0]
 [ 3 11  2]
 [ 0  0  6]]


In [36]:
# Create LDA

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda=LDA()
lda_x=lda.fit_transform(sc_x,y)
display(pd.DataFrame(lda_x))


0         1
0    4.700244  1.979138
1    4.301958  1.170413
2    3.420720  1.429101
3    4.205754  4.002871
4    1.509982  0.451224
..        ...       ...
173 -4.291508  3.390332
174 -4.503296  2.083546
175 -5.047470  3.196231
176 -4.276155  2.431388
177 -5.538086  3.042057

[178 rows x 2 columns]

In [39]:
# Display the Variance Percentage

display(lda.explained_variance_ratio_)

array([0.68747889, 0.31252111])

In [40]:
# Train Test Split

from sklearn.model_selection import train_test_split
lda_x_train,lda_x_test,y_train,y_test=train_test_split(lda_x,y,test_size=0.2,random_state=0)
print(lda_x.shape)
print(lda_x_train.shape)
print(lda_x_test.shape)

(178, 2)
(142, 2)
(36, 2)


In [42]:
# Create Logistic Regression

from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(lda_x_train,y_train)



LogisticRegression(random_state=0)

In [43]:
# Prediction

y_pred=classifier.predict(lda_x_test)
print(y_pred)

[1 3 2 1 2 2 1 3 2 2 3 3 1 2 3 2 1 1 2 1 2 1 1 2 2 2 2 2 2 3 1 1 2 1 1 1]


In [45]:
# Confusion matrix and Accuracy Score

from sklearn.metrics import confusion_matrix,accuracy_score
print(accuracy_score(y_pred,y_test))
cm=confusion_matrix(y_pred,y_test)
print(cm)

1.0
[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]


In [46]:
(14+16+6)/36

1.0

In [47]:
# LDA with One variable

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda=LDA(n_components=1)
lda_x=lda.fit_transform(sc_x,y)
display(pd.DataFrame(lda_x))


0
0    4.700244
1    4.301958
2    3.420720
3    4.205754
4    1.509982
..        ...
173 -4.291508
174 -4.503296
175 -5.047470
176 -4.276155
177 -5.538086

[178 rows x 1 columns]

In [48]:
# Explained Variance Ratio

display(pd.DataFrame(pca.explained_variance_ratio_))

0
0  0.361988

In [49]:
# Train Test Split

from sklearn.model_selection import train_test_split
lda_x_train,lda_x_test,y_train,y_test=train_test_split(lda_x,y,test_size=0.2,random_state=0)
print(lda_x.shape)
print(lda_x_train.shape)
print(lda_x_test.shape)

(178, 1)
(142, 1)
(36, 1)


In [50]:
# Create Logistic Regression

from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(lda_x_train,y_train)



LogisticRegression(random_state=0)

In [51]:
# Prediction

y_pred=classifier.predict(lda_x_test)
print(y_pred)

[1 3 2 2 2 1 1 3 2 2 3 3 1 1 3 2 1 1 3 1 1 1 2 2 2 2 2 2 2 3 1 1 2 1 1 1]


In [52]:
# Confusion matrix and Accuracy Score

from sklearn.metrics import confusion_matrix,accuracy_score
print(accuracy_score(y_pred,y_test))
cm=confusion_matrix(y_pred,y_test)
print(cm)

0.8333333333333334
[[12  3  0]
 [ 2 12  0]
 [ 0  1  6]]


In [53]:
# Model without LDA

# Train Test Split

# Train Test Split

from sklearn.model_selection import train_test_split
sc_x_train,sc_x_test,y_train,y_test=train_test_split(sc_x,y,test_size=0.2,random_state=0)
print(sc_x.shape)
print(sc_x_train.shape)
print(sc_x_test.shape)

(178, 13)
(142, 13)
(36, 13)


In [54]:
# Create Logistic Regression

from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(sc_x_train,y_train)



LogisticRegression(random_state=0)

In [56]:
# Prediction

y_pred=classifier.predict(sc_x_test)
print(y_pred)

[1 3 2 1 2 2 1 3 2 2 3 3 1 2 3 2 1 1 2 1 2 1 1 2 2 2 2 2 2 3 1 1 2 1 1 1]


In [57]:
# Confusion Matrix and Accuracy Score

from sklearn.metrics import confusion_matrix,accuracy_score
print(accuracy_score(y_pred,y_test))
cm=confusion_matrix(y_pred,y_test)
print(cm)


1.0
[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]


In [59]:
(14+16+6)/36

1.0

In [ ]:
'''Ok Prajwal 👽'''